-- AlterTable
ALTER TABLE `tb_agendamentos` ADD COLUMN `endereco` VARCHAR(191) NULL,
    ADD COLUMN `linkMeet` VARCHAR(191) NULL,
    ADD COLUMN `tipoConsulta` ENUM('ONLINE', 'PRESENCIAL') NOT NULL DEFAULT 'PRESENCIAL',
    MODIFY `valorPago` DECIMAL(10, 2) NULL,
    MODIFY `status` ENUM('AGUARDANDO_PAGAMENTO', 'AGENDADO', 'CONFIRMADO', 'REALIZADO', 'CANCELADO_COM_CREDITO', 'CANCELADO') NOT NULL DEFAULT 'AGUARDANDO_PAGAMENTO';

-- AlterTable
ALTER TABLE `tb_usuarios` MODIFY `tipo` ENUM('ADMIN', 'NUTRICIONISTA', 'PACIENTE') NOT NULL DEFAULT 'PACIENTE';
